name: Build Maven (reusable) ga

on:
  workflow_call:
    inputs:
      java-version:
        type: string
        default: '17'
        description: 'Versión de Java a usar'
      distribution:
        type: string
        default: 'temurin'
        description: 'Distribución del JDK'
      mvn-args:
        type: string
        default: 'clean package -DskipTests'
        description: 'Comando/args de Maven'
      upload-artifact:
        type: boolean
        default: true
        description: 'Subir artefacto compilado'
      artifact-name:
        type: string
        default: 'artifact'
        description: 'Nombre del artefacto'
      artifact-path:
        type: string
        default: 'target/*.jar'
        description: 'Ruta del artefacto a subir'
    secrets:
      github-token:
        required: false

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
    steps:
      - uses: actions/checkout@v4

      - name: Setup Java ${{ inputs.java-version }}
        uses: actions/setup-java@v4
        with:
          distribution: ${{ inputs.distribution }}
          java-version: ${{ inputs.java-version }}
          cache: 'maven'

      - name: Build with Maven
        run: mvn ${{ inputs.mvn-args }}

      - name: Upload build artifact
        if: ${{ inputs.upload-artifact }}
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.artifact-name }}
          path: ${{ inputs.artifact-path }}
