name: Build and Push to Google - ga

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Java JDK 17
      uses: actions/setup-java@v4
      with:
        distribution: 'temurin'
        java-version: '17'
        
    - name: Build with Maven
      run: mvn clean package -DskipTests
      
    - name: Set up Google Cloud CLI
      uses: 'google-github-actions/auth@v2'
      with:
        credentials_json: '${{ secrets.GCP_SA_KEY }}'

    - name: Configure Docker for Google Artifact Registry
      run: |
        gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: Set imagen name
      id: vars
      run: echo "IMAGE_NAME=us-central1-docker.pkg.dev/hypnotic-epoch-411523/cna-github/$(basename ${{ github.repository }})" > "$GITHUB_ENV"

    - name: Build the Docker image
      run: docker build -t $IMAGE_NAME:latest .

    - name: Push Docker image
      run: docker push $IMAGE_NAME:latest

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy $(basename ${{ github.repository }}) \
          --image $IMAGE_NAME:latest \
          --region us-central1 \
          --platform managed \
          --allow-unauthenticated
